### ISSUE TITLE
Change bar label colour if dark

### ISSUE THREAD

**Issue by TickboxPhil** [wishyoulization/PowerBI-visuals-BarChartRace#10]
Would be great to have contrasting label colours - can't have black text on dark bars as they're unreadable!

![image](https://user-images.githubusercontent.com/16966543/78797304-6b9e5e00-79af-11ea-8382-51be1fbac8c9.png)

**Comment by a10k** [comment]
https://github.com/wishyoulization/PowerBI-visuals-BarChartRace/commit/eddef392deb0a37bba2316748252b63ef79d85a2
