### ISSUE TITLE
Using date - appears as 0 in bottom right corner

### ISSUE THREAD

**Issue by nbrown02** [wishyoulization/PowerBI-visuals-BarChartRace#9]
Trying to create a visualization for a dataset over a year period, instead of the year in the bottom right I want to show the date. Currently this is just a 0
![image](https://user-images.githubusercontent.com/29369962/78230742-aee96000-74c9-11ea-8dda-e7e7cd6ad23e.png)

**Comment by TickboxPhil** [comment]
Second that, great visual but practically useless if it only does year - need it to do full date (ie daily) at least, or any contiguous numbers!
![image](https://user-images.githubusercontent.com/16966543/78797098-28dc8600-79af-11ea-9d3b-f6365d6f5f61.png)

**Comment by alano444** [comment]
Technically you can do daily. Create a new calculated column 
DatePeriod=(([Year Month Whole Number][Year]*100)+[Month])+Day
and use this for the period.  The Period on the chart will appear as 20201201, 20201202, ... which is not the prettiest but it works

**Comment by alano444** [comment]
I just realized that github is ahead of the Power BI app source version.  There is a new chart property "Period Label (Formatted Text)".  Create a second Calculated column of type text with the period format you want e.g. "21 Jan 2020" and add it to Period Label.
This is the bomb!
